import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'; //

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
        <nav>
  <Link href="/" className="mr-4">Home</Link>
  <Link href="/AppRouterPage" className="mr-4">App Router</Link>
  <Link href="/FilePage" className="mr-4">NextJS Files</Link>
  <Link href="/ServerComponentsPage">Server Components</Link>
</nav>

        </header>
        {children}
      </body>
    </html>
  );
}